version: '3.5'
services:
  modsecurity:
    network_mode: host
    build: .
    container_name: sentinel
    hostname: sentinel
    image: sentinel
    restart: always
    volumes:
      - ./logs:/var/log/apache2
    entrypoint:
      - /bin/sh
      - -c
      - '/bin/bash /app/entrypoint.sh'
#    ports: 
#    - "9595:9696"
    
